version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    ports:
      - "8083:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
